project:
  type: website

website:
  title: "Analise de cluster"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Análise.qmd
      - Aplicação cluster.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



